### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SourinMajumdar**
Added 1 row for the actual 'lesson 1' at the beginning of the table (As per the listing of lessons in our Udacity classroom)

x

### CODE REVIEW

**Comment by SourinMajumdar** [comment]
I would also like to know the relevance behind 'Udacity SUSE Cloud Native' in the table. Kindly provide an overview.

**Comment by xxprime** [comment]
> I would also like to know the relevance behind 'Udacity SUSE Cloud Native' in the table. Kindly provide an overview.

Oh yeah the correct heading should be: ```Udacity AWS Machine Learning Foundations Nanodegree Program```

**Comment by SourinMajumdar** [comment]
> > I would also like to know the relevance behind 'Udacity SUSE Cloud Native' in the table. Kindly provide an overview.
> 
> Oh yeah the correct heading should be: `Udacity AWS Machine Learning Foundations Nanodegree Program`

So I have changed it to this:  `Udacity AWS Machine Learning Foundations Nanodegree Program`.

Hope you merge them !

**Review by xxprime — APPROVED** [review]
I think the reason @Shivansh2407 omitted the first lesson is because it's just a "welcome to the course" type thing. But I think this is better so that we won't get confused with the lesson numbers. Changes are good by me! Ship it! @Shivansh2407 :shipit:

**Comment by SourinMajumdar** [comment]
> I think the reason @Shivansh2407 omitted the first lesson is because it's just a "welcome to the course" type thing. But I think this is better so that we won't get confused with the lesson numbers. Changes are good by me! Ship it! @Shivansh2407 :shipit:

I got confused at the beginning, I was about to mark 'comeplete' the lesson which I didn't even start. So this confusion might happen for many others. So I did this. Thank tho : ) @xxprime

**Comment by Shivansh2407** [comment]
> I would also like to know the relevance behind 'Udacity SUSE Cloud Native' in the table. Kindly provide an overview.

Oops! Thanks for noticing and correcting it. It was a bit typo because of managing the other related repos 😄

And yeah, @xxprime I thought first lesson is a welcome kind thing, so let's proceed with other lessons. But if that's confusing, we can surely merge this and correct the table!

Thank you all 🎉 and Happy Contributing ✨

**Comment by SourinMajumdar** [comment]
> > I would also like to know the relevance behind 'Udacity SUSE Cloud Native' in the table. Kindly provide an overview.
> 
> Oops! Thanks for noticing and correcting it. It was a bit typo because of managing the other related repos 😄
> 
> And yeah, @xxprime I thought first lesson is a welcome kind thing, so let's proceed with other lessons. But if that's confusing, we can surely merge this and correct the table!
> 
> Thank you all 🎉 and Happy Contributing ✨

Thank you ! Happy Learning ✨

**Review by Shivansh2407 — APPROVED** [review]
LGTM 🎉✨ Great Work @SourinMajumdar ✨

**Pull request merged**
